### ISSUE TITLE
Cosign login

### ISSUE THREAD

**Issue by kubik369** [fmfi-svt/votr#112]
Posledné cca dva dni sa nejde prihlásiť. Login redirect skončí s 503 na tejto adrese `https://votr.uniba.sk/cosign/valid?cosign-proxy-votr.uniba.sk=5pGgXgmothyAUlexFjYx9jfOhye-kQXm4Rkv+lE4amZpeP4g61NkFrmfXl7kryErGmGWXub26BQyvlxGYtKh30jmv5gWixXvBaHdZ0v0dZxm4LTEbDkOHaBdTPIp&https://votr.uniba.sk/proxylogin?server=0&destination=`

**Comment by TomiBelan** [comment]
Vypršal nám cosign certifikát. :( Pracuje sa na tom.

**Comment by TomiBelan** [comment]
Fixed!
