### ISSUE TITLE
MobileTables v MojeSkusky - pretekanie cez okraj

### ISSUE THREAD

**Issue by Adman** [fmfi-svt/votr#136]
V casti MojeSkusky trochu preteka tabulka, co sposobuje, ze ked sa chcem prihlasit na skusku, musim najprv scrollnut doprava. cc @alolapo 

Prikladam aj screenshoot.
![51935341_2141293715947066_697691534287437824_n](https://user-images.githubusercontent.com/865063/52564444-85243400-2e04-11e9-8feb-18cf67a47a13.jpg)

**Comment by alolapo** [comment]
Dakujem za feedback, pozriem na to.

Dňa po 11. 2. 2019, 12:54 Adrián Matejov <notifications@github.com>
napísal(a):
