### ISSUE TITLE
Mobile: Button "Stiahnut ako iCal" je zobrazeny cez kalendar v mesiacovom mode

### ISSUE THREAD

**Issue by Adman** [fmfi-svt/votr#155]
Ked prepnem na zobrazenie celeho mesiaca v mobile, tak ten button je zobrazeny cez posledny riadok. Pri zobrazeni tyzdna/dna sa tento problem nevyskytuje. Problem je iba na mobilnom zariadeni.

**Comment by TomiBelan** [comment]
Vdaka za report!

V akom browseri?

Robi to to iste aj v desktopovom browseri (chrome / firefox), ked mu v developer tools povies nech sa tvari ako mobil?

**Comment by Adman** [comment]
Na desktope vo firefoxe a chromium to nerobi. V mobile pouzivam Chrome. Teraz som ho ale updatol na najnovsiu verziu a zda sa, ze sa to fixlo same :).
