### ISSUE TITLE
Aplikacia VSES007 Terminy hodnotenia nemusi mat ziadne zaznamy

### ISSUE THREAD

**Issue by kikoval** [fmfi-svt/votr#58]
Ak neexistuje ziaden zaznam, po aplikovani filtra sa objavi upozornenie "Podmienkam nevyhovuje žiadny záznam.", co nie je osetrene.

Problem je vo funkcii `__vyber_oba_semestre()` v triede `WebuiTerminyMixin` (votr/fladgejt/webui/terminy.py).

**Comment by TomiBelan** [comment]
Fixnute v d447669423596c9c311d957c961bf6cc78f68daf.
