### ISSUE TITLE
Opakovane zapisany predmet v "Moje hodnotenia"

### ISSUE THREAD

**Issue by PaLy** [fmfi-svt/votr#61]
...sa v tabulke vyskytuje len raz (prvy zapis). Ak usortim predmety podla hodnotenia zostupne, tak mam pri nom hodnotenie FX (prvy zapis), ak usortim vzostupne, tak mam A (druhy zapis).

**Comment by TomiBelan** [comment]
Fakt, dakujeme za report. Prosim chod na https://votr.uniba.sk/beta/ a vyskusaj, ci je to fixnute. Potom v noci to dam aj na ostru verziu.

**Comment by PaLy** [comment]
Vyzera, ze vsetko funguje.

**Comment by TomiBelan** [comment]
Pushnute a deploynute na https://votr.uniba.sk/.
