### ISSUE TITLE
Kontrolovat ze register predmetov sme otvorili prihlaseni

### ISSUE THREAD

**Issue by TomiBelan** [fmfi-svt/votr#63]
Chyba: `RPC get_studenti_zapisani_na_predmet failed with AISBehaviorError`
`aisikl.exceptions.AISBehaviorError: We expected ['openDialog'] but AIS did something different: []`

O co ide:
Register predmetov (VSST060) moze otvorit aj neprihlaseny pouzivatel, a moze kludne hladat predmety a pozerat si ich informacne listy, ale nemoze si pozriet zoznam prihlasenych studentov.
Normalne si vsimneme, ak nam vyprsi AIS login, lebo pride chyba "Neprihlásený prístup!". Ale register predmetov sa normalne otvori, len tam nebudeme prihlaseni.

Kontrolu, ze sme prihlaseni, by sme asi mali pridat priamo do get_studenti_zapisani_na_predmet (a thrownut LoggedOutError). Ostatne funkcie, co pouzivaju register predmetov, nezaujima ci sme prihlaseni.

Rozdiely medzi prihlasenym a odhlasenym dialogom:
- vyskytPredmetuVStudPlanochMenuItem a poctyPrihlasenychStudentovMenuItem maju `enabled='false'`
- printButton a exportButton maju `enabled='false' disabled='disabled'`
- infoButton ma text `Anonymný používateľ` (v title a alt obsahuje `&nbsp;`)
- printAction, exportAction, vyskytPredmetuVStudPlanochAction, poctyPrihlasenychStudentovAction maju `accessible='false'` namiesto `accessible='true'`

**Comment by svklum** [comment]
Tato issue vyzera byt jemne blizka issue #76 do ktorej uz nieco robim, mal by som preto asi zaujem sa pozriet aj na toto ak je to este stale aktualne?! Vzhladom na zmeny vykonane okolo LogOutErrorov je popis vyssie stale aktualny?

**Comment by TomiBelan** [comment]
Je to trochu blizke, aj ked iba jemne. Kludne sa pozri aj na toto. Popis je stale aktualny.

Ked to budes testovat, mozno sa vhodnym hackovitym vykomentovanim kodu da dosiahnut ze budes prihlaseny do Votru ale nevykona sa to co ta naozaj prihlasi do AISu (a skontroluje to), aby si nemusel cakat n hodin. Z hlavy neviem presne.

**Comment by TomiBelan** [comment]
Ach jo... tri roky otvoreny issue a dvojriadkovy fix...

Upratujem logy prikazom:
`sudo -u www-data venv/bin/python console.py log tag +%issue63 -%open $( vlog list -c get_studenti_zapisani_na_predmet 'AISBehaviorError: We expected \[.openDialog.\] but AIS did something different: \[\]' )`
