### ISSUE TITLE
Moje hodnotenia - sucet kreditov

### ISSUE THREAD

**Issue by kovacspeter** [fmfi-svt/votr#67]
Sucet kreditov nie je dobry zapocita tam aj kredity z predmetov kde student dostal Fx

**Comment by TomiBelan** [comment]
Deploynute.

@kovacspeter, mozes potvrdit, ze uz vidno spravny sucet?

**Comment by kovacspeter** [comment]
@TomiBelan jop uz je to spravne. Skvela praca.
