### ISSUE TITLE
Chybajuce fonty/zle zobrazene znaky

### ISSUE THREAD

**Issue by mhozza** [fmfi-svt/votr#69]
V prvom stlpci je zahadny stvorcek - tipujem ze tam ma byt nieco smysluplnejsie.
![screenshot 2015-06-07 19 43 10](https://cloud.githubusercontent.com/assets/1177655/8025222/d96ca6ae-0d4d-11e5-8417-95aeb687fc1f.png)

**Comment by TomiBelan** [comment]
Su to http://www.fileformat.info/info/unicode/char/2714/index.htm a http://www.fileformat.info/info/unicode/char/2718/index.htm. Ktory windows je to? Smutne ze ich nema by default...

Zhanat kvoli tomu webfont je trochu overkill. Nevies ako by sa dal zistit zoznam znakov co su podporovane vo windowsovych defaultnych fontoch?

**Comment by mhozza** [comment]
je to windows 10 a netusim ako zistit zoznam znakov. Ale mozno do finalnej verzie daju lepsie fonty, ale moc by som sa nestavil.

**Comment by AnotherKamila** [comment]
To je úplne zúfalé, hentie znaky by vážne všetko malo mať. To by hádam mohli opraviť, to predsa musí byť bug, nie feature.

**Comment by TomiBelan** [comment]
Overil som, ze Windows 8.1 tie znaky ma (font je Arial). Ak uz mas finalny Windows 10, mozes zistit, ci s tym ma stale problem?

**Comment by TomiBelan** [comment]
Zase raz ping @mhozza. :-) Ukazuje v desiatkach Votr stale stvorceky?
(Pseudo upratujem zoznam issues...)

**Comment by mhozza** [comment]
sorry, checknem ked niekedy naladujem windows.

**Comment by mhozza** [comment]
Vyzera ze to funguje.
