### ISSUE TITLE
Lepsi error ked vyprsi AIS (alebo REST) login

### ISSUE THREAD

**Issue by TomiBelan** [fmfi-svt/votr#76]
Ked vyprsi AIS login, uzivatel uvidi velky skaredy AISBehaviorError o tom ako AIS nespravil co sme cakali ale zobrazil messageBox s textom "Neautorizovaný prístup!". Mal by to byt LoggedOutError a uzivatel by mal vidiet peknu hlasku.

Treba:
- Novu metodu `awaited_open_main_dialog_or_login_expired`, ktora v pripade messageBoxu vyhodi vhodny LoggedOutError (s textom daneho messageBoxu), a inak zavola `awaited_open_main_dialog`.
- Obdobnu zmenu v `_open_register_osob`. (Ledaze by nieco trosku ine, aby sme neduplikovali kod?)
- Ukazovat pri LoggedOutError pekny popis aj po RPC, nielen pri neprazdnom `Votr.settings.error`. To je dolezite aj ked vyprsi REST login.
- Zrusit logovacie pravidlo `%unauthorized` a updatnut wiki.

**Comment by svklum** [comment]
Zdravim, mal by som zaujem sa pozriet na tuto issue. Aktualne mi po vyprsani AISu vyhodi chybu aka je v prilozenom obrazku.
Zaujimalo by ma ci je tento problem este aktualny alebo na tom uz niekto pracoval a chyba ktoru mi to vyhadzuje po vyprsani je ziaduca (nevypisuje sa totiz "Neautorizovany pristup!" a hore v sedom policku na pozadi vidiet v popise ze sa jedna o LoggedOutError )

![chybavotr](https://user-images.githubusercontent.com/29373075/27083986-54c50bb6-5018-11e7-9523-840a239df0d5.png)

**Comment by TomiBelan** [comment]
Go for it! Takto to nemá vyzerať :-)

Tento bug sú dva bugy v jednom. Konkrétna chyba závisí od toho, či prvý request po vypršaní loginu ide cez AIS alebo cez REST. Ak otvoríš Votr, n hodín počkáš, a klikneš na Moje predmety, dostaneš tvoj screenshot. Ak otvoríš Votr, n hodín počkáš, a klikneš na Register predmetov, dostaneš od AISu "Neautorizovaný prístup!". Obe chyby by bolo dobré spraviť krajšie.

(Ale oboje by malo nastať iba ak už bol Votr dlho otvorený. Keď ho otváraš alebo refreshuješ, mal by skontrolovať vypršaný login a ukázať pekný error. Je to tak?)

Hore je veľmi hrubý návod, ako fixnúť oboje. Asi nie veľmi zrozumiteľný :D tak skúsim znovu.

Pre REST login je to ľahké, na serveri už sa vyhadzuje správny exception, len ho na klientovi zle ukazujeme. V ErrorPage.js sa riešia dva druhy chýb: tie pri prihlásení (čo dostaneme vo Votr.settings.error) a tie z AJAXu. Treba preusporiadať tie ify, aby sa LoggedOutError ukazoval v oboch prípadoch rovnako.

Pre AIS login je to zložitejšie. Prečítaj si dokumentáciu o Aisikl (viď linka v README, trochu stará), zvlášť čo sú operations. Ako tak čítam logy, vyzerá že AIS pri vypršanom logine vždy vráti presne tri `ops` s metódami `serverCloseApplication, messageBox, closeApplication`. To by sa dalo detekovať v `Application.open` a vtedy vyhadzovať LoggedOutError. (Hore som navrhoval novú metódu, ale vlastne ju netreba. A keď sa to bude kontrolovať v `Application.open`, bude to fungovať aj pre register osôb.)
