### ISSUE TITLE
Vytvaranie zapisnych listov

### ISSUE THREAD

**Issue by TomiBelan** [fmfi-svt/votr#93]
Na zaciatku skolskeho roka musi student spravit dve veci: vyrobit si zapisny list, a zapisat si predmety ake chce. To druhe uz Votr vie, to prve este nie.

Vo `fladgejt/webui/studium.py` uz existuju `create_zapisny_list` a `delete_zapisny_list`. (A tiez `get_akademicke_roky_noveho_zapisneho_listu` a `get_roky_studia_noveho_zapisneho_listu`.) Ale treba k nim spravit UI. (A mozno zjednodusit API? Nie som si isty, ci `create_zapisny_list` naozaj potrebuje tolko parametrov, zvlast ak ma AIS dobre defaulty ktore nikdy netreba menit.)

**Comment by mrshu** [comment]
Toto by sme asi mohli skusit spravit -- vzhladom na aktualne AISove skusenosti by to nemuselo byt tak velmi narocne (cc @ViRPo @Adman)

**Comment by Adman** [comment]
https://github.com/fmfi-svt/votr/pull/125
