### ISSUE TITLE
Zmena v programe AIS2

### ISSUE THREAD

**Issue by Dzusifruit** [fmfi-svt/votr#96]
Nakoľko sa inovovalo AIS2 na Komenského, tak takmer žiadna funkcia nie je dostupná.

**Comment by mrshu** [comment]
@Dzusifruit Vdaka za report, pokusime sa problem v co najkratsom case vyriesit.

**Comment by mrshu** [comment]
Pripomeniem, ze je vyhadzovana tato chyba:

```
AISParseError: Couldn't parse script line: if (VSST010_SpravaDatumAkciiDlg0DlgJSO!=null) VSST010_SpravaDatumAkciiDlg0DlgJSO.tryAutosize()
```
